; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Common library dependencies
[common]
lib_deps = 
	arduino-libraries/Ethernet@^2.0.2
	knolleary/PubSubClient@^2.8
	https://github.com/thijse/Arduino-Log
	agdl/Base64@^1.0.0
	bblanchon/ArduinoJson@^7.0.4
	lasselukkari/aWOT@^3.5.0
	matmunk/DS18B20@^1.0.0
	paulstoffregen/OneWire@^2.3.8
	hafidh/FlowSensor@^1.5.0

[env:atmega2560]
platform = atmelavr
board = megaatmega2560
monitor_raw = true
monitor_speed = 115200
framework = arduino
board_build.mcu = atmega2560
board_build.f_cpu = 16000000L
lib_deps = ${common.lib_deps}

; OTA environment for AVR over Ethernet
[env:atmega2560_ota]
platform = atmelavr
board = megaatmega2560
framework = arduino
board_build.mcu = atmega2560
board_build.f_cpu = 16000000L
lib_deps = ${common.lib_deps}
upload_protocol = custom
upload_port = 192.168.1.92:8266
upload_flags =
    --host=$UPLOAD_PORT
    --file=$SOURCE
extra_scripts = post:upload_ota.py

[env:STM32F103RET6]
platform = ststm32
framework = arduino
board = genericSTM32F103RE
board_build.mcu = stm32f103ret6
monitor_raw = true
monitor_speed = 115200
build_flags = 
	-O2
	-D__STM32__
build_unflags = -Os
upload_protocol = jlink
board_build.f_cpu = 64000000L
lib_deps = 
	${common.lib_deps}
	koendv/RTT Stream@^1.4.1

; OTA environment for STM32 over Ethernet
[env:STM32F103RET6_ota]
platform = ststm32
framework = arduino
board = genericSTM32F103RE
board_build.mcu = stm32f103ret6
monitor_raw = true
monitor_speed = 115200
build_flags = 
	-O2
	-D__STM32__
build_unflags = -Os
upload_protocol = custom
upload_port = 192.168.1.92:8266
upload_flags =
    --host=$UPLOAD_PORT
    --file=$SOURCE
board_build.f_cpu = 64000000L
lib_deps = 
	${common.lib_deps}
	koendv/RTT Stream@^1.4.1
extra_scripts = post:upload_ota.py